name:                deriving-via
version:             0.1.0.0
github:              "dnadales/sandbox/deriving-via"
license:             BSD3
author:              "Damian Nadales"
maintainer:          "damian.nadales@gmail.com"
copyright:           "Copyright: (c) 2018 Damian Nadales"

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - QuickCheck


tests:
  deriving-via-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:    
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deriving-via
