name:                quickcheck-vs-hedgehog
version:             0.1.0.0
github:              "dnadales/sandbox/quickcheck-vs-hedgehog"
license:             BSD3
author:              "Damian Nadales"
maintainer:          "damian.nadales@gmail.com"
copyright:           "Copyright: (c) 2019 Damian Nadales"

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

benchmarks:
  quickcheck-vs-hedgehog-bench:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - hedgehog >= 1.0
    - QuickCheck
    - text
    - transformers

tests:
  large-shrink-space:
    main: Main.hs
    source-dirs: test/large-shrink-space/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - hedgehog >= 1.0
    - QuickCheck
