name:                thinking-with-types
version:             0.1.0.0
github:              "dnadales/sandbox/thinking-with-types"
license:             BSD3
author:              "Damian Nadales"
maintainer:          "damian.nadales@gmail.com"
copyright:           "Copyright: (c) 2018 Damian Nadales"

dependencies:
- base >= 4.7 && < 5
- first-class-families
- vector

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies: []
