name: hello-haskell-stack # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: An example on how to package a Haskell application into a snap. # 79 char long summary
description: |
  This application prints a message and quits. It is intended to show how a
  Haskell application built with stack can be packaged into a snap. 
  
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots.
                     # This means that this snap can only be published to the
                     # hidden "edge" mode.
                     
parts:
  hello-haskell-stack:
    # See 'snapcraft plugins'
    plugin: dump
    source: .stack-work/install/x86_64-linux-nopie/lts-9.10/8.0.2/bin/

apps:
  hello-haskell-stack:
    command: hello-haskell-stack-exe
