name:                qcsm-echo
version:             0.1.0.0
github:              "dnadales/sandbox/qcsm-echo"
license:             BSD3
author:              "Damian Nadales"
maintainer:          "damian.nadales@gmail.com"
copyright:           "Copyright: (c) 2018 Damian Nadales"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: []

tests:
  qcsm-echo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:    
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qcsm-echo
    - quickcheck-state-machine
    - hspec
    - QuickCheck
    - tree-diff
